<?php
/**
 * Created by PhpStorm.
 * User: kandan
 * Date: 28/02/2014
 * Time: 4:51 PM
 */

?>

<!-- Include the jQuery library (local or CDN) -->
<script src="http://code.jquery.com/jquery-latest.min.js"></script>

<!-- Include the plugin *after* the jQuery library -->
<script src="<?php bloginfo('stylesheet_directory'); ?>/includes/bjqs/bjqs-1.3.min.js"></script>

<!-- Include the basic styles -->
<link type="text/css" rel="Stylesheet" href="<?php bloginfo('stylesheet_directory'); ?>/includes/bjqs/bjqs.css" />